### ISSUE TITLE
updating to Appdeamon4 stops this from operating correctly ?

### ISSUE THREAD

**Issue by Mariusthvdb** [ludeeus/ad-address#1]
Hi Ludeeus,

since we worked on this some time ago, this has been working perfectly. Now I updated to Appdeamon4 today, and the app address seems to have stopped doing its magic.

Would you be so kind as to see why this would be?

Is all starts up correctly (do get  for this:

```
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
)

error in the logs:
```
2020-01-16 11:24:15.186232 WARNING address: Unexpected error in worker for App address:
2020-01-16 11:24:15.187151 WARNING address: Worker Ags: {'id': 'redacted25f9cf8b5da74b5be63a6a7d0566a', 'name': 'address', 'objectid': 'redacted40af235cf9abad41a46436c7376f', 'type': 'state', 'function': <bound method Address.get_address of <address.Address object at 0xb5280d48>>, 'attribute': 'state', 'entity': 'device_tracker.life360_marijn', 'new_state': 'not_home', 'old_state': 'home', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2020-01-16 11:24:15.188611 WARNING address: ------------------------------------------------------------
2020-01-16 11:24:15.196667 WARNING address: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/address/address.py", line 35, in get_address
    lat = self.get_state(entity=entity, attribute="latitude")
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1310, in get_state
    return await self.AD.state.get_state(
TypeError: get_state() got an unexpected keyword argument 'entity'
```

as far as I can see here https://appdaemon.readthedocs.io/en/latest/HISTORY.html there is no change to cause this error? reverted to AD3 and it automatically starts working again...

__update__
see @renetode 's remarks about an omission in the breaking changes:
https://community.home-assistant.io/t/community-hass-io-add-on-appdaemon-4/163259/21?u=mariusthvdb

**Comment by ludeeus** [comment]
This was written for AD3.
I can not guarantee that it will work for AD4.
Setting up that is not high on my list.
If you (or anyone else) figure it out, please submit a PR for it.

**Comment by ReneTode** [comment]
i created a PR that should work in AD 4.

**Comment by Mariusthvdb** [comment]
ok great, where can I see it Rene?
btw check @petro s change suggestions in the community thread. I applied those, but still no such luck unfortunately. No errors, but no result either ....

__edit__

wait, I now see it was already merged.... quick!

doesn't work though. still no error, and no result. tried Petro's change too, without any difference.

just to be complete and sure, this app config would still be according to new specs?:
```
address:
  module: address
  class: Address
  entity:
    - device_tracker.life360_marijn
    - device_tracker.life360_2
    - device_tracker.life360_3
    - device_tracker.life360_4
    - device_tracker.life360_5
    - device_tracker.life360_6
```

**Comment by Mariusthvdb** [comment]
think this one can be closed, because AD 4 runs it fine now. DO have another issue in current HA 117, so Ill create a new issue
